name: aura3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  intl: ^0.20.2
  syncfusion_flutter_charts: ^31.2.5
  syncfusion_flutter_core: ^31.2.5
  awesome_notifications: ^0.10.1
  printing: ^5.10.0
  pdf: ^3.10.1
dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_native_splash: ^2.3.6


flutter:
  uses-material-design: true
  
  assets:
    - assets/
